import type { NotificationScheduler } from './scheduler';

export const notificationScheduler: NotificationScheduler = {
  supported: false,
  getPermission: async () => 'granted',
  ensurePermission: async () => 'granted',
  getDiagnostics: async () => ({
    permission: 'granted',
    appNotificationsEnabled: true,
    exactAlarm: 'not-applicable',
    fullScreen: 'not-applicable',
    channel: 'not-applicable',
    channelImportance: null,
    soundEnabled: null,
    vibrationEnabled: null,
    floatingBanner: 'not-applicable',
    scheduledCount: 0,
    registeredCount: 0,
    lastTestScheduledAt: 0,
    lastTestTriggerAt: 0,
    lastDeliveryAt: 0,
    lastDeliveryIdentifier: '',
  }),
  replace: async (reminders) => reminders.length,
  clear: async () => {},
  sendImmediateTest: async () => 'web-preview',
  scheduleDelayedTest: async () => ({ identifier: 'web-preview', triggerAt: Date.now() + 60_000 }),
  openNotificationSettings: async () => {},
  openExactAlarmSettings: async () => {},
  openFullScreenIntentSettings: async () => {},
  openBatterySettings: async () => {},
};
